title: My Data Science Workstation
description: Docker image with all you need for data science.
author: Israel Oliveira <prof.israel@gmail.com>
version: 2.3.0
PORT_JUPYTERLAB: 9988
PORT_STREAMLIT: 9901
PORT_FREE: 9990
APP_NAME: my-ds-d2l
CONTAINER_NAME: ws-d2l
BASE_IMAGE_NAME: python
BASE_IMAGE_TAG: 3.9-bullseye
SHM_SIZE: 16g
DOCKER_HOST: tcp://docker:2375
DOCKER_ACCOUNT: ysraell
